### ISSUE TITLE
Support native namespace packages

### ISSUE THREAD

**Issue by ericof** [reinout/z3c.dependencychecker#120]
@gforcada: We should support native namespace packages or disable this checking on plone/meta:

Ref: https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages

**Comment by gforcada** [comment]
Indeed, we are looking for `__init__.py` files as a way to _optimize_ the scanning face.

We are skipping `node_modules`, but if we remove this, we should also look for `.tox`, `venv` and all its variants, etc.

Maybe only start looking for python code either in `src` or the package name? 🤔

**Comment by ericof** [comment]
@gforcada What about importing the code, getting the base directory and then starting from there?

**Comment by ericof** [comment]
@gforcada I would say you must process `setup.py`(and `pyproject.toml` in the future) to find the correct path to the package codebase.

**Comment by gforcada** [comment]
Yes, maybe, let's see, for now we are not importing it at all, just to avoid having to install it etc etc, which makes it running `z3c.dependencychecker` much faster.

Given that we have a configuration section on `pyproject.toml` we could try to guess the root folder, and otherwise fallback and say: `"Please add config option XXX to point to the source root 🙇🏾 "`

**Comment by gforcada** [comment]
Turns out that we are already using a good enough (at least so far 🤞🏾 ) heuristics: we look at the `.egg-info` dir and read the `top_level.txt` file to see where the source code is ✨
