### ISSUE TITLE
Package hiding others

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#98]
Not sure how this can actually be solved:

We have plenty of packages that depend on `Zope2`, that is fine, and as for `import` statements and such, with the mappings, all is good.

But since `Zope` is no longer on version 2 but rather on 5, the package got renamed to `Zope`.

Now if a package depends on `zope.schema` and `zope.interface` but also on `Zope` itself, `z3c.dependencychecker` fails to recognize that `zope.interface` and `zope.schema` are missing from `setup.py` since the package depends on `Zope` 💥 😱 

Since in this case [Zope](https://github.com/zopefoundation/Zope/tree/master/src) only is an umbrella and has no direct code, could we single it out in `z3c.dependencychecker`? 🍀 

And whenever another package does the same (let's say `Plone` 😅 ) we could add a key on `pyproject.toml` configuration that allows to list umbrella packages that provide no code on their own namespace? 🤔 

Ideas?

**Comment by reinout** [comment]
I think it is fine to have an exception for `zope`. It definitively isn't normal practice, so.... it is an exception.
Zope is something with a long history and, like plone, it is from the era when namespace packages were all the rage.

It isn't used that much nowadays, so I don't think we have to fear many extra exceptions.

So.... my first thought would be an `if` in the code instead of an extra key in `pyproject.toml`. Probably easier and quicker to do?

**Comment by gforcada** [comment]
Yes, by all means 👍🏾 and if you already expect that to be a really corner case, then let's do it this way, and if more pop up, then we can think about it again
